apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
      - cluster: prod
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/SimonMisencik/helm-charts.git
        targetRevision: HEAD
        path: "charts/basic-app"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{cluster}}-guestbook"
          valuesObject:  
            ingress:
              enabled: true
              annotations:
                kubernetes.io/ingress.class: nginx
              hosts:
                - host: "{{cluster}}-a.127.0.0.1.nip.io"
                  paths:
                    - path: /
                      pathType: Prefix
            image:
              repository: nginxdemos/hello
              pullPolicy: IfNotPresent
              # Overrides the image tag whose default is the chart appVersion.
              tag: "0.4"
              port: 80
      destination:
        server: https://kubernetes.default.svc
        namespace: guestbook
